__default__:
    cpus-per-task: 2
    mem-per-cpu: 4G
    partition: fast
    output: '{log.output}_cluster'
    error: '{log.error}_cluster'
    job-name: '{rule}.{wildcards}'

bwa_index:
    cpus-per-task: 1

run_atropos:
    cpus-per-task: 6

run_fastqc:
    cpus-per-task: 2

run_bwa_aln_PE:
    cpus-per-task: 6
    mem-per-cpu: 4G
    partition: long

bwa_sampe_sort_bam:
    cpus-per-task: 6
    mem-per-cpu: 4G
    partition: long

bwa_mem_sort_bam:
    cpus-per-task: 6
    mem-per-cpu: 4G
    partition: long

samtools_index:
    cpus-per-task: 1

samtools_idxstats:
    cpus-per-task: 4
    mem-per-cpu: 4G


samtools_depth:
    mem-per-cpu: 4G

merge_idxstats:
    cpus-per-task: 1
    mem-per-cpu: 30G

bam_stats_to_csv:
    mem-per-cpu: 20G

merge_bam_stats:
    cpus-per-task: 1

picardTools_mark_duplicates:
    cpus-per-task: 1
    mem-per-cpu: 20G
    partition: long

gatk_HaplotypeCaller:
    cpus-per-task: 4
    mem-per-cpu: 40G
    partition: long

gatk_GenomicsDBImport:
    cpus-per-task: 1
    mem-per-cpu: 40G
    partition: long


gatk_GenotypeGVCFs_merge:
    cpus-per-task: 1
    mem-per-cpu: 40G
    partition: long

create_sequence_dict:
    cpus-per-task: 1
    mem-per-cpu: 10G

bcftools_concat:
    cpus-per-task: 10

report:
    cpus-per-task: 1

report_vcf:
    cpus-per-task: 1
    mem-per-cpu: 90G

vcf_to_fasta:
    cpus-per-task: 1

vcf_to_geno:
    cpus-per-task: 1

vcftools_filter:
    cpus-per-task: 1

run_raxml:
    cpus-per-task: 20

run_raxml_ng:
    cpus-per-task: 15

vcf_stats:
    mem-per-cpu: 30G
