# Master RattleSNP configuration file template
# ------------------------------------------

################################
# Input output data options
DATA:
    FASTQ: "DATA_DIR/fastq/"
    BAM: ""
    VCF: ""
    REFERENCE_FILE: "DATA_DIR/reference/FR1067.fasta"
    OUTPUT: "DATA_DIR/output"

PARAMS:
    MITOCHONDRIAL_NAME : ""
    # The filter suffix to add on vcf filter in order to allow multiple filter
    FILTER_SUFFIX: ["-Q30-DP5-MAF005-MISS07",
                    "-Q30-DP20-MAF001-MISS05"]

################################
# Pipeline tools activation
FASTQC: true
CLEANING:
    ATROPOS: true
MAPPING:
    ACTIVATE: true
    TOOL: "BWA_MEM"         # Use BWA_MEM or BWA_SAMPE only
    BUILD_STATS: true      # warning if true but mapping false, mapping automatically run
SNPCALLING: true
FILTER: true                # Must be true if want run raxml or raxml-ng
RAXML: true
RAXML_NG: true

### TODO post analyse tools like SNMF, RAXML, ...
################################
# Misc. options for programs
PARAMS_TOOLS:
    ATROPOS: "--minimum-length 35  -q 20,20  -U 8  -O 10"
    FASTQC: ""
    BWA_ALN: ""
    BWA_SAMPE: ""
    BWA_MEM: ""
    SAMTOOLS_VIEW: "-bh -f 2"
    SAMTOOLS_SORT: ""
    SAMTOOLS_DEPTH: ""
    PICARDTOOLS_MARK_DUPLICATES: "-CREATE_INDEX TRUE -VALIDATION_STRINGENCY SILENT"
    GATK_HAPLOTYPECALLER: "--java-options '-Xmx40G' --emit-ref-confidence GVCF --output-mode EMIT_ALL_ACTIVE_SITES -ploidy 1"
    GATK_GENOMICSDBIMPORT: "--java-options '-Xmx40G' "
    GATK_GENOTYPEGVCFS: "--java-options '-Xmx40G' -new-qual"
    VCFTOOLS: ["--minDP 5 --minQ 30 --remove-indels --recode --recode-INFO-all --maf 0.05 --max-missing 0.7",
               "--minDP 20 --minQ 30 --remove-indels --recode --recode-INFO-all --maf 0.01 --max-missing 0.5"]
    RAXML: "-m GTRGAMMAX -f a -x $RANDOM -# autoMRE -p 600"
    RAXML_NG: "--all --model GTR+G --tree pars{50},rand{50} --bs-trees 100 --seed $RANDOM"
