version: 2


# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py


submodules:
  include: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - r-base-core

# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.9
   install:
      - method: pip
        path: .
        extra_requirements:
          - docs
   system_packages: true
